# Generated by Django 4.0.6 on 2023-07-06 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_lot_id', models.CharField(max_length=30)),
                ('parking_lot_name', models.CharField(max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=250)),
                ('parking_lot', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.parking_lot')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('shift_id', models.IntegerField()),
                ('date', models.DateField()),
                ('total', models.FloatField(editable=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.payment_machine')),
            ],
            options={
                'unique_together': {('operation_id', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Operation_hoopers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hooper_id', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('count', models.IntegerField()),
                ('currency', models.CharField(max_length=30)),
                ('operation_type', models.CharField(max_length=30)),
                ('total', models.FloatField(editable=False)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.operations')),
            ],
            options={
                'unique_together': {('hooper_id', 'operation', 'operation_type')},
            },
        ),
    ]
